name = "postglide"
version = "1.0.0"
target = "javascript"

description = "Gleam bindings to PGlite, a WASM build of Postgres for client-side browser applications"
licences = ["Apache-2.0"]
repository = { type = "github", user = "george-grec", repo = "postglide" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_javascript = ">= 1.0.0 and < 2.0.0"
